- name: create install dir
  file: dest={{ gradle.install_path }} state=directory
  tags:
    - gradle

- set_fact:
  gradle_package_name: gradle-{{ gradle.version }}-bin.zip
  tags:
    - gradle

- name: check gradle package
  stat: path={{ package_download_path }}/{{ gradle_package_name }}
  register: gradle_package_exists
  tags:
    - gradle

- name: download gradle package
  get_url: url={{ gradle.download_mirror }}/{{ gradle_package_name }} dest={{ package_download_path }}
  when: not gradle_package_exists.stat.exists
  tags:
    - gradle

- name: unarchive gradle package
  unarchive: src={{ package_download_path }}/{{ gradle_package_name }} dest={{ gradle.install_path }} copy=no 
  tags:
    - gradle

- set_fact:
  gradle_bin_path: {{ gradle.install_path }}/gradle-{{ gradle.version }}/bin/gradle
  tags:
    - gradle

- name: set symlink to gradle bin
  file: src={{ gradle_bin_path }} dest=/usr/bin/gradle state=link
  tags:
    - gradle
